title = "Optional field if the app has a full title (leave blank if there is no full title)"

#For App Domains aim to use one that has already been used and try to be as general as possible
appDomain = ["1","Or more ","Scientific domains that the app fits into (this will be used to categorise the app)"]
sources = [["My github page","https://github.com/Mxtt-smith/"],["My linkedIn","https://www.linkedin.com/in/matthew-smith-0b8842282/"]] 
description = """This is a suitable description of my experiments,
 the configurations of applications X,Y & Z and 
 some filler to illustrate how a description might look on the page: 
 In the heart of the cosmos, where wonders collide,
  Particles dance in a mystical tide. Minuscule marvels,unseen by the eye, 
  They waltz through the void where the galaxies lie. 
  Electrons and protons in orbits they spin, Neutrons, 
  the glue that holds atoms within. Quarks in their triplets, 
  in colors they blend, Gluons, the messengers, forces they send. 
  Photons of light in their infinite flight, 
  Travel through time, painting day into night."""
