title = "Vector Particle-in-Cell"
appDomain = ["Particle-in-Cell", "Structured Grid"]
sources = [["VPIC GitHub","https://github.com/lanl/vpic"], ["VPIC 2.0 GitHub", "https://github.com/lanl/vpic-kokkos"]] 
description = """
VPIC is a general purpose particle-in-cell simulation code for modeling kinetic plasmas in one, two, or three spatial dimensions. 
It employs a second-order, explicit, leapfrog algorithm to update charged particle positions and velocities in order to solve the relativistic kinetic equation for each species in the plasma, along with a full Maxwell description for the electric and magnetic fields evolved via a second-order finite-difference-time-domain (FDTD) solve. 
The VPIC code has been optimized for modern computing architectures and uses Message Passing Interface (MPI) calls for multi-node application as well as data parallelism using threads. 
VPIC employs a variety of short-vector, single-instruction-multiple-data (SIMD) intrinsics for high performance and has been designed so that the data structures align with cache boundaries.

VPIC is a 3D3V, fully relativistic, kinetic, performance-first PIC code for solving the coupled Maxwell-Boltzmann system of equations. 

VPIC 2.0 utilizes the Kokkos performance-portable framework, VPIC achieves high performance on multiple CPU and GPU architectures.
"""