---
name: Pull request checks
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  Directory_checks:
    runs-on: ubuntu-latest
    name: Directory structure checks
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: checkout repo content
        uses: actions/checkout@v4
        
      - name: Run toml.py
        run: |
          python .github/submissionScripts/directoryStructure.py

  Toml_checks:
    runs-on: ubuntu-latest
    needs: Directory_checks
    name: Toml Validation
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: checkout repo content
        uses: actions/checkout@v4
        
      - name: Run toml.py
        run: |
          python .github/submissionScripts/toml.py
  
